---
version: 2
build:
  os: ubuntu-20.04
  tools:
    python: "3.10"
  jobs:
    pre_build:
      - ./devel/rtd-pre-build
sphinx:
  configuration: doc/conf.py
  builder: dirhtml
python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - dev
