sudo: false

services:
  - docker

language: python
cache: pip

node_js: "12"

addons:
  apt:
    update: true
    packages:
      - mafft
      - iqtree
      - raxml
      - fasttree
      - vcftools
      - snakemake

matrix:
  include:
    - dist: xenial
      python: 3.5
      name: "Ubuntu Xenial, Python 3.5"

    - dist: xenial
      python: 3.6
      name: "Ubuntu Xenial, Python 3.6"

    - dist: xenial
      python: 3.7
      name: "Ubuntu Xenial, Python 3.7"

    - dist: xenial
      python: 3.8
      name: "Ubuntu Xenial, Python 3.8"

    - dist: xenial
      python: 3.8-dev
      name: "Ubuntu Xenial, Python 3.8-dev"

    - dist: bionic
      python: 3.6
      name: "Ubuntu Bionic, Python 3.6"

    - dist: bionic
      python: 3.7
      name: "Ubuntu Bionic, Python 3.7"

    - dist: bionic
      python: 3.8
      name: "Ubuntu Bionic, Python 3.8"

    - dist: bionic
      python: 3.8-dev
      name: "Ubuntu Bionic, Python 3.8-dev"

install:
  - pip3 install .
  - pip3 install flake8 mypy nextstrain-augur
  - npm install --global auspice

before_script:
  - git clone https://github.com/nextstrain/zika-tutorial

script:
  - flake8
  - mypy nextstrain
  - nextstrain version
  - nextstrain check-setup
  - nextstrain update
  - nextstrain build zika-tutorial
