sudo: required

services:
  - docker

language: python

addons:
  apt:
    update: true

matrix:
  include:
    - dist: trusty
      python: 3.6.1

    - dist: xenial
      python: 3.5

    - dist: xenial
      python: 3.6

    - dist: xenial
      python: 3.7

    - dist: xenial
      python: 3.8

    - dist: xenial
      python: 3.8-dev

    - dist: bionic
      python: 3.6

    - dist: bionic
      python: 3.7

    - dist: bionic
      python: 3.8

    - dist: bionic
      python: 3.8-dev

install:
  - pip3 install .
  - pip3 install flake8 mypy

before_script:
  - git clone https://github.com/nextstrain/zika-tutorial

script:
  - flake8
  - mypy nextstrain
  - nextstrain version
  - nextstrain check-setup
  - nextstrain update
  - nextstrain build zika-tutorial
