name: Run integration tests
description: >-
  Runs integration tests excercising common commands and behaviour.

  Jobs which use this action must have

    1. Called the setup-integration-tests action.
    2. Installed Nextstrain CLI on the PATH.

  before calling this action.

inputs:
  ambient:
    description: Flag to enable/disable the ambient runtime integration test steps
    default: "true"

runs:
  using: composite
  steps:
    - shell: bash -l -eo pipefail {0}
      run: nextstrain version --verbose

    - if: runner.os != 'macOS' && runner.os != 'Windows'
      shell: bash -l -eo pipefail {0}
      run: nextstrain setup docker

    - if: runner.os != 'Windows'
      shell: bash -l -eo pipefail {0}
      run: nextstrain setup conda

    - if: runner.os != 'macOS' && runner.os != 'Windows'
      shell: bash -l -eo pipefail {0}
      run: nextstrain setup singularity

    - shell: bash -l -eo pipefail {0}
      run: nextstrain check-setup --set-default

    - shell: bash -l -eo pipefail {0}
      run: nextstrain version --verbose

    - if: runner.os != 'macOS' && runner.os != 'Windows'
      name: Build zika-tutorial with --docker
      shell: bash -l -eo pipefail {0}
      run: |
        git -C zika-tutorial clean -dfqx
        nextstrain build --docker --cpus 2 zika-tutorial

    - if: runner.os != 'Windows'
      name: Build zika-tutorial with --conda
      shell: bash -l -eo pipefail {0}
      run: |
        git -C zika-tutorial clean -dfqx
        nextstrain build --conda --cpus 2 zika-tutorial

    - if: runner.os != 'macOS' && runner.os != 'Windows'
      name: Build zika-tutorial with --singularity
      shell: bash -l -eo pipefail {0}
      run: |
        git -C zika-tutorial clean -dfqx
        nextstrain build --singularity --cpus 2 zika-tutorial

    - if: fromJSON(inputs.ambient) && runner.os != 'Windows'
      name: Build zika-tutorial with --ambient
      shell: bash -l -eo pipefail {0}
      run: |
        git -C zika-tutorial clean -dfqx
        nextstrain build --ambient --cpus 2 zika-tutorial
