#!/bin/bash
base="$(realpath "$(dirname "$0")/..")"
doc="$base/doc"
lib="$base/nextstrain/cli"

main() {
    pushd "$doc"
        rebuild
        while inotifywait -e attrib -r . "$lib"; do
            rebuild
        done
    popd
}

rebuild() {
    make clean
    make dirhtml

    pushd _build/dirhtml
        kill %
        python3 -m http.server &
        trap 'kill %' EXIT
    popd
}

main "$@"
