#!/bin/bash
set -euo pipefail

base="$(cd "$(dirname "$0")/.."; pwd)"
venv="$base/.venv"

set -x
rm -rf "$venv"
python3.6 -m venv "$venv"
"$venv"/bin/pip install --upgrade pip setuptools wheel pip-tools
"$venv"/bin/pip install -e '.[dev]'
